### ISSUE TITLE
rpassword doesn't compile with rustc 1.85.1

### ISSUE THREAD

**Issue by nwalfield** [conradkleinespel/rpassword#130]
According to [the project's `Cargo.toml`](https://github.com/conradkleinespel/rpassword/blob/main/Cargo.toml), `rpassword` MSRV is 1.85.  However, `rpassword` 7.5.2 does not actually compile with 1.85.  Compile Sequoia (which has an MSRV of 1.85), I see:

```
$ rustc --version
rustc 1.85.1 (4eb161250 2025-03-15)
$ cargo check
...
error[E0658]: `let` expressions in this position are unstable
  --> /home/us/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rpassword-7.5.2/src/unix.rs:49:12
   |
49 |         if let Some(fd) = self.input_fd
   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
  --> /home/us/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rpassword-7.5.2/src/unix.rs:50:16
   |
50 |             && let Some(ref mut term_orig) = self.input_term_orig
   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
...
```

For now, I've gone back to 7.4.0, however, it would be nice to fix this (preferably for Sequoia by keeping an MSRV of 1.85; we try and keep our MSRV at whatever version of `rustc` Debian ships in their stable distribution for as long as possible).

**Comment by conradkleinespel** [comment]
Hi, thanks for reporting. I agree we should stick to 1.85 as in Debian.

If anyone can jump in and do the following things in a PR, that would help out a lot:

- update the Github Actions config to use Rust 1.85
- update the code that breaks under Rust 1.85

I'm unavailable to work on this for a few days but can review merge a PR with passing tests.

**Comment by conradkleinespel** [comment]
Working on this now.

**Comment by conradkleinespel** [comment]
Just published the fix in 7.5.3. Let me know if you still encounter any issues. Cheers!

**Comment by nwalfield** [comment]
Thank you for working on this.  I've just confirmed that rpassword 7.5.2 fails to compile with rustc 1.85.1, but compiles correctly with 7.5.3.
